services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    image: nginx:alpine
    volumes:
      - ../frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
